### PR TITLE
Add specific test for clarification

### PR DESCRIPTION
**Pull request by agilecreativity**
Hi @gigasquid,

I just like to point out one simple test case for clojure-case.
Is this by designed or if this is special case that we should address.

Thanks for a great library.

### CODE REVIEW

**Comment by gigasquid** [comment]
Thanks for bringing up the test case. In practice, we haven't run into a problem with the code yet because all the Scala code uses the Camel Case or underscores. But, we should fix the function so that it returns `foo-bar`. 

Are you interested in fixing the code so that it would pass that test case? No pressure, if not - I'll pick it up :)

**Comment by agilecreativity** [comment]
@gigasquid 
Code fixed, and squashed to one commit.
Cheers,

**Comment by gigasquid** [comment]
Thanks for the help! I'd like to add you to the README under the special thanks section. Should I list you as agilecreativity, Burin Choomnuan, or something else. It's also perfectly fine if you'd prefer not to be listed. Just let me know.

**Comment by agilecreativity** [comment]
You can list me as Burin Choomnuan is ok.
Thanks

**Pull request merged**
