### PR TITLE
Improve style with cljfmt

### PR DESCRIPTION
**Pull request by agilecreativity**
Hi @gigasquid,

Let's improve the style with the help of cljfmt tools.
The PR, include re-usable scripts that will allow us to use the same styles for all of the code.

Note the scripts is included but not yet applied to any codes.
If you like me to proceed to apply the changes please let me know.

Thanks

### CODE REVIEW

**Comment by gigasquid** [comment]
Thanks for the PR. It looks good 😸 

I think this is a good solution to put the plugin in now, but not apply the formatting yet, to keep the diff small until it the PR gets merged into the main repo.

I'll give it a test drive shortly 🚗

**Comment by agilecreativity** [comment]
Forgot to mentioned that you can use two commands

```sh
# To check the style and see what will be changed/updated in the console
# without actually making any changes
lein-cljfmt-check

# And when you are ready to commit the changes
lein-cljfmt-fix
```

**Comment by gigasquid** [comment]
Thanks @agilecreativity  - I took it for a test drive and I really liked it ❤️ . Thinking about it more, I think that it would be nice to have the code that was formatted by the plugin along with the plugin commits. I'm asking the reviewers in the PR on MXNet if they would like it included in the initial PR or an add on one once it gets merged.

If it's to be after the first PR gets merged, I'll keep this PR open until I got the code in a PR over there.

**Comment by gigasquid** [comment]
Hey @agilecreativity - the clojure-package has been merged to the main project! Yay!

Do you want me to go ahead and open a PR with these changes over there or would you like to do it under your own github name and get involved as a contributor there? Either is fine with me, just let me know your preference. Thanks again for being patient with getting this change in :)

**Comment by agilecreativity** [comment]
@gigasquid 

I am super excited to see the main project get merged to the main branch.
I am closing this PR, and create the new PR against the main project [https://github.com/apache/incubator-mxnet/pull/11514](https://github.com/apache/incubator-mxnet/pull/11514).

Would love to see your initial review and see if you like me to improve or adjust anything.

Best,
Burin

**Pull request closed without merging**
