### PR TITLE
Improve styles with cljfmt

### PR DESCRIPTION
**Pull request by agilecreativity**
Hi @gigasquid 

Leverage [cljfmt](https://github.com/weavejester/cljfmt) as ways for us to use the same style for the codebase starting with the example codes. The last commit contains the script that I use

- `lein cljfmt fix` #=> run the fix

#### Benefit:

Everyone who would be contributor can use different editor (Emacs/Vim/Cursive, etc) but we can still contribute using the same style.

The script used:

```sh
#!/usr/bin/env bash
for dir in $(find . -type d -depth 1 | grep -v scripts)
do
  cd $dir
  lein cljfmt fix
  cd ..
done
```
In this PR, I added `lein-cljfmt` to the plugins vector and then create two simple scripts
one to check for style, and the other for fixing the style automatically.

It is very configurable and can be adjusted to your preferred styles if you like. More information can be found in the [cljfmt's readme](https://github.com/weavejester/cljfmt/blob/master/README.md) file.

Please note that I only apply the script to the examples projects, but leave the main project intact.
If you are ok with this then you can run the script in the base directory (one for check one for fix style).

As it will probably changes most of the code (excluding the generated file), so I leave it up to you
to decide if you want to do it. Or if you want I can create a new PR to contain the result of applying the script to the main src/test codes.

Thanks
Burin

### CODE REVIEW

**Comment by agilecreativity** [comment]
Hi @gigasquid,

I add two more scripts to the main project, it is slightly different than the ones in examples parts

- lein-cljfmt-check
- lein-cljfmt-fix

If you are ok feel free to apply the change using the `lein-cljfmt-fix` script.
Or let me know if you like me to adjust anything.

Best,

**Comment by gigasquid** [comment]
I like the changes ❤️ 

The only problem right now is logistical in how to get them in the codebase with the open PR that I have against the main project https://github.com/apache/incubator-mxnet/pull/11205. 

Right now, I've been keep this repo in sync with the PR until it gets merged. After it gets merged, I will get rid of the code here and all contributions with be taken in the apache project. As the PR is under review right now, I've agreed to keep the changesets to it small to not overwhelm the reviewers. 

I think the formatting changes would be better suited to a separate PR against that repo since it will cause a big diff.

If you could hold off on your changes on your branch until that gets merged and then open one against the apache mxnet repo that would be awesome! It will be a great place for you and others to get involved. I have a few more unit tests to boost the coverage for that PR and then I'm _hoping_ it will get merged in the next week.

Thanks for your help and involvement 😸

**Comment by agilecreativity** [comment]
I did not realized you have open PR against the main project. So I am definitely would not like to cause the big diff to the reviewer.

I will hold off and wait for things to get merged then.

Thanks

**Comment by agilecreativity** [comment]
Close this for now.

**Pull request closed without merging**
